custom-configuration:
  property1: property_1_test
  property2: property_2_test
  connection_string: jdbc://postgresql/localhost:5432/employee_db

spring:
  jpa:
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/employee_db?currentSchema=public
    username: postgres
    password:
    driver-class-name: org.postgresql.Driver


